name: Docker Build and Push

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Build and push
      env:
        IMAGE_NAME: your_image_name
        VERSION: v1.0.0
      run: |
        docker build -t ghcr.io/USERNAME/IMAGE_NAME:VERSION .
        docker push ghcr.io/USERNAME/IMAGE_NAME:VERSION
