name: Publish Docker image

on:
 push:
    branches:
      - 'main' 

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker build
        run: docker build -t ghcr.io/Reversbtw/danil:1.0 .

      - name: Docker push
        run: docker push ghcr.io/Reversbtw/danil:1.0

  run_image:
    name: Run Docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    needs: push_to_registries
    steps:
      - run: docker run ghcr.io/Reversbtw/danil:1.0
      - run: ssh 'reversbtw-danil-wkzgduq4ls3#-fAfbSOIkbZx4iUaSCd7fzH.gSqIZwGg@reversbtw-danil-wkzgduq4ls3.ssh.ws-eu106.gitpod.io' "cd /workspace/nke-template && docker compose pull && docker compose up -d"
